name: "Ai PR summarizer"
description: "Ai enabled summarizer for PRs"
author: "bemijonathan"

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: "Your input description here"
#     required: true
#     default: "1000"

# # Define your outputs here.
# outputs:
#   time:
#     description: "Your output description here"

runs:
  using: node16
  main: dist/index.js
