name: "atropellar"
description: "Langchain summary for PR"
author: "bemijonathan"

inputs:
  gitHubToken:
    description: "GitHub token"
    required: true
  openAIKey:
    description: "OpenAI key"
    required: true

branding:
  color: "blue"
  icon: "align-left"
runs:
  using: node20
  main: dist/index.js
