name: "woot ai"
description: "Woot ai 🚂 helps you check your jira ticket against your code base"
author: "bemijonathan"

inputs:
  gitHubToken:
    description: "GitHub token"
    required: true
  openAIKey:
    description: "OpenAI key"
    required: true
  jiraEmail:
    description: "jira email associated with the api key"
    required: true
  jiraApiKey:
    description: "jira access api key"
    required: true
  jiraHost:
    description: "jira host endpoint"
    required: true

branding:
  color: "blue"
  icon: "align-left"
runs:
  using: node20
  main: dist/index.js
