name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      - name: Commit dist Directory
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist
          git commit -m 'Add built dist directory'
          git push origin main

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          gitHubToken: ${{ secrets.GIT_HUB_TOKEN }}
          openAIKey: ${{ secrets.OPENAI_API_KEY }}
          # Jira credentials
          jiraEmail: ${{ secrets.JIRA_EMAIL }}
          jiraApiKey: ${{ secrets.JIRA_API_KEY }}
          jiraHost: ${{ secrets.JIRA_HOST }}
          # trello credentials
          # trelloPublicKey: ${{ secrets.TRELLO_PUBLIC_KEY }}
          # trelloPrivateKey: ${{ secrets.TRELLO_PRIVATE_KEY }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
